server:
  port: 8080
  tomcat.uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        # \u4F7F\u7528druid\u6570\u636E\u6E90
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        encoding: utf-8
        mode: HTML5
        content-type: text/html
        cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lin.workitem.model

#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql